plugins {
    id 'java'
}

group = 'com.jtcg'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
}

test {
    useJUnitPlatform()
}

jar {
    archiveFileName = 'jtcg.jar'
    manifest {
        attributes(
                'Main-Class': 'com.jtcg.cli.TestCodeGeneratorApp'
        )
    }
}
